stages:
  preprocessing:
    cmd: python scripts/preprocessing.py
    wdir: .
    deps:
    - data/raw_data
    - scripts/preprocessing.py
    params:
    - preprocessing.file_names
    - preprocessing.start_file
    - preprocessing.target_file
    outs:
    - data/preprocessed_data/preprocessed_data_amazonn.json
  analyze:
    cmd: papermill scripts/analyze.ipynb data/notebooks/analyzed.ipynb
    deps:
    - data/preprocessed_data
    - scripts/analyze.ipynb
    params:
    - preprocessing.file_names
    - preprocessing.start_file
    - preprocessing.target_file
    metrics:
    - data/notebooks/analyzed.ipynb:
        cache: false
  split:
    cmd: python scripts/split.py
    deps:
    - data/processed_data
    - scripts/split.py
    params:
    - preprocessing.target_file
    - split.target_file_test
    - split.target_file_train
    - class_column_name
    outs:
    - data/test/test_raw.json
    - data/train/train_raw.json
  extraction:
    cmd: python scripts/extraction.py
    deps:
    - data/test/test_raw.json
    - data/train/train_raw.json
    - scripts/extraction.py
    params:
    - split.target_file_train
    - split.target_file_test
    - extraction.target_file_train
    - extraction.target_file_test
    outs:
    - data/train/train_extracted.json
    - data/test/test_extracted.json
  learn_and_evaluation:
    cmd: python scripts/learn_and_evaluation.py
    deps:
    - data/test/test_extracted.json
    - data/train/train_extracted.json
    - scripts/learn_and_evaluation.py
    params:
    - class_column_name
    - extraction.target_file_train
    - extraction.target_file_test
    - learn_and_evaluation.target_file
    - learn_and_evaluation.method
    - learn_and_evaluation.model
    - learn_and_evaluation.selection
    - learn_and_evaluation.reduction
    metrics:
    - data/results/results_cross.json:
        cache: false



